# Generates allah_names.json with the 99 Names of Allah.
# Names follow the commonly accepted list (as-Sa'di order is popular; here we use
# the widely published 99 names with accurate Arabic, transliteration, and meaning).
import json

names = [
    (1, "الرحمن", "Ar-Rahman", "The Most Merciful", "The Beneficent, the Most Gracious whose mercy encompasses all creation."),
    (2, "الرحيم", "Ar-Raheem", "The Most Compassionate", "The Most Merciful to the believers in particular."),
    (3, "الملك", "Al-Malik", "The King", "The Sovereign Lord, owner of all dominion."),
    (4, "القدوس", "Al-Quddus", "The Holy", "The Pure, free from all imperfection."),
    (5, "السلام", "As-Salam", "The Source of Peace", "The Giver of peace and security."),
    (6, "المؤمن", "Al-Mu'min", "The Giver of Faith", "The One who grants security and confirms faith."),
    (7, "المهيمن", "Al-Muhaymin", "The Guardian", "The Protector and Watcher over all things."),
    (8, "العزيز", "Al-Azeez", "The Almighty", "The Exalted in Might, the Victorious."),
    (9, "الجبار", "Al-Jabbar", "The Compeller", "The One who restores and compels according to His will."),
    (10, "المتكبر", "Al-Mutakabbir", "The Majestic", "The Supreme in grandeur and majesty."),
    (11, "الخالق", "Al-Khaliq", "The Creator", "The One who creates everything from nothing."),
    (12, "البارئ", "Al-Bari'", "The Evolver", "The One who fashions creation and gives it form."),
    (13, "المصور", "Al-Musawwir", "The Fashioner", "The One who shapes and designs all forms."),
    (14, "الغفار", "Al-Ghaffar", "The Ever-Forgiving", "The One who repeatedly forgives sins."),
    (15, "القهار", "Al-Qahhar", "The Subduer", "The One who dominates and overcomes all."),
    (16, "الوهاب", "Al-Wahhab", "The Bestower", "The One who gives freely and abundantly."),
    (17, "الرزاق", "Ar-Razzaq", "The Provider", "The One who provides sustenance for all."),
    (18, "الفتاح", "Al-Fattah", "The Opener", "The One who opens doors of mercy and judgment."),
    (19, "العليم", "Al-'Aleem", "The All-Knowing", "The One who knows all things."),
    (20, "القابض", "Al-Qabid", "The Withholder", "The One who constricts and withholds."),
    (21, "الباسط", "Al-Basit", "The Expander", "The One who expands and gives abundantly."),
    (22, "الخافض", "Al-Khafid", "The Abaser", "The One who lowers and humbles."),
    (23, "الرافع", "Ar-Rafi'", "The Exalter", "The One who raises and elevates."),
    (24, "المعز", "Al-Mu'izz", "The Honorer", "The One who grants honor and dignity."),
    (25, "المذل", "Al-Mudhill", "The Humiliator", "The One who humbles the arrogant."),
    (26, "السميع", "As-Sami'", "The All-Hearing", "The One who hears all things."),
    (27, "البصير", "Al-Baseer", "The All-Seeing", "The One who sees all things."),
    (28, "الحكم", "Al-Hakam", "The Judge", "The One who judges with perfect justice."),
    (29, "العدل", "Al-'Adl", "The Just", "The One who is entirely just."),
    (30, "اللطيف", "Al-Lateef", "The Subtle", "The One who is kind and gentle, aware of the finest details."),
    (31, "الخبير", "Al-Khabeer", "The All-Aware", "The One who is fully acquainted with all matters."),
    (32, "الحليم", "Al-Haleem", "The Forbearing", "The One who is patient and slow to punish."),
    (33, "العظيم", "Al-'Azeem", "The Magnificent", "The One of infinite greatness."),
    (34, "الغفور", "Al-Ghafoor", "The Forgiving", "The One who forgives completely."),
    (35, "الشكور", "Ash-Shakoor", "The Appreciative", "The One who rewards gratitude abundantly."),
    (36, "العلي", "Al-'Aliyy", "The Most High", "The One exalted above all."),
    (37, "الكبير", "Al-Kabeer", "The Most Great", "The One who is greater than all."),
    (38, "الحفيظ", "Al-Hafeez", "The Preserver", "The One who protects and preserves all."),
    (39, "المقيت", "Al-Muqeet", "The Sustainer", "The One who provides nourishment and power."),
    (40, "الحسيب", "Al-Haseeb", "The Reckoner", "The One who takes account of all."),
    (41, "الجليل", "Al-Jaleel", "The Majestic", "The One of supreme glory and majesty."),
    (42, "الكريم", "Al-Kareem", "The Generous", "The One who is infinitely generous."),
    (43, "الرقيب", "Ar-Raqeeb", "The Watchful", "The One who watches over all."),
    (44, "المجيب", "Al-Mujeeb", "The Responsive", "The One who answers prayers."),
    (45, "الواسع", "Al-Wasi'", "The Vast", "The One whose capacity and mercy are boundless."),
    (46, "الحكيم", "Al-Hakeem", "The Wise", "The One who is perfectly wise."),
    (47, "الودود", "Al-Wadud", "The Loving", "The One who loves the righteous."),
    (48, "المجيد", "Al-Majeed", "The Glorious", "The One of infinite glory."),
    (49, "الباعث", "Al-Ba'ith", "The Resurrector", "The One who raises the dead."),
    (50, "الشهيد", "Ash-Shaheed", "The Witness", "The One who witnesses all things."),
    (51, "الحق", "Al-Haqq", "The Truth", "The One whose existence is absolute truth."),
    (52, "الوكيل", "Al-Wakeel", "The Trustee", "The One who manages all affairs."),
    (53, "القوي", "Al-Qawiyy", "The Strong", "The One of perfect strength."),
    (54, "المتين", "Al-Mateen", "The Firm", "The One of firmness and steadfastness."),
    (55, "الولي", "Al-Waliyy", "The Protecting Friend", "The One who supports the believers."),
    (56, "الحميد", "Al-Hameed", "The Praiseworthy", "The One who is worthy of all praise."),
    (57, "المحصي", "Al-Muhsi", "The Accounter", "The One who enumerates all things."),
    (58, "المبدئ", "Al-Mubdi'", "The Originator", "The One who begins creation."),
    (59, "المعيد", "Al-Mu'id", "The Restorer", "The One who repeats and restores creation."),
    (60, "المحيي", "Al-Muhyi", "The Giver of Life", "The One who grants life."),
    (61, "المميت", "Al-Mumeet", "The Taker of Life", "The One who causes death."),
    (62, "الحي", "Al-Hayy", "The Ever-Living", "The One who is eternally alive."),
    (63, "القيوم", "Al-Qayyum", "The Self-Sustaining", "The One who sustains all existence."),
    (64, "الواجد", "Al-Wajid", "The Finder", "The One who finds all that is sought."),
    (65, "الماجد", "Al-Majid", "The Noble", "The One of perfect nobility."),
    (66, "الواحد", "Al-Wahid", "The One", "The One without partner."),
    (67, "الأحد", "Al-Ahad", "The Unique", "The One who is indivisible and unique."),
    (68, "الصمد", "As-Samad", "The Eternal Refuge", "The One who is sought in every need."),
    (69, "القادر", "Al-Qadir", "The All-Powerful", "The One who is able to do all things."),
    (70, "المقتدر", "Al-Muqtadir", "The Determiner", "The One who determines all with power."),
    (71, "المقدم", "Al-Muqaddim", "The Advancer", "The One who advances whom He wills."),
    (72, "المؤخر", "Al-Mu'akhkhir", "The Deferrer", "The One who delays whom He wills."),
    (73, "الأول", "Al-Awwal", "The First", "The One who is before all."),
    (74, "الآخر", "Al-Akhir", "The Last", "The One who remains after all."),
    (75, "الظاهر", "Az-Zahir", "The Manifest", "The One whose existence is evident."),
    (76, "الباطن", "Al-Batin", "The Hidden", "The One who is beyond perception."),
    (77, "الوالي", "Al-Wali", "The Governor", "The One who governs all affairs."),
    (78, "المتعالي", "Al-Muta'ali", "The Exalted", "The One who is far above all imperfection."),
    (79, "البر", "Al-Barr", "The Source of Goodness", "The One who is kind and good to all."),
    (80, "التواب", "At-Tawwab", "The Acceptor of Repentance", "The One who accepts repentance repeatedly."),
    (81, "المنتقم", "Al-Muntaqim", "The Avenger", "The One who punishes the wrongdoers."),
    (82, "العفو", "Al-'Afuww", "The Pardoner", "The One who pardons sins."),
    (83, "الرءوف", "Ar-Ra'uf", "The Most Kind", "The One who is gentle and compassionate."),
    (84, "مالك الملك", "Malik-ul-Mulk", "The Owner of All Sovereignty", "The One who owns all dominion."),
    (85, "ذو الجلال والإكرام", "Dhul-Jalali wal-Ikram", "The Lord of Majesty and Honor", "The One of glory and generosity."),
    (86, "المقسط", "Al-Muqsit", "The Equitable", "The One who is just and fair."),
    (87, "الجامع", "Al-Jami'", "The Gatherer", "The One who gathers all creation."),
    (88, "الغني", "Al-Ghaniyy", "The Self-Sufficient", "The One who is free of all need."),
    (89, "المغني", "Al-Mughni", "The Enricher", "The One who enriches whom He wills."),
    (90, "المانع", "Al-Mani'", "The Preventer", "The One who prevents and protects."),
    (91, "الضار", "Ad-Darr", "The Distresser", "The One who brings benefit and harm by His wisdom."),
    (92, "النافع", "An-Nafi'", "The Benefactor", "The One who brings benefit."),
    (93, "النور", "An-Nur", "The Light", "The One who guides with light."),
    (94, "الهادي", "Al-Hadi", "The Guide", "The One who guides to the truth."),
    (95, "البديع", "Al-Badi'", "The Originator", "The One who creates without precedent."),
    (96, "الباقي", "Al-Baqi", "The Everlasting", "The One who remains forever."),
    (97, "الوارث", "Al-Warith", "The Inheritor", "The One who inherits all."),
    (98, "الرشيد", "Ar-Rashid", "The Guide to the Right Path", "The One who guides to what is right."),
    (99, "الصبور", "As-Sabur", "The Patient", "The One who is infinitely patient.")
]

data = {"names": [{
    "number": n, "arabicName": ar, "transliteration": tr,
    "meaning": mn, "description": desc
} for n, ar, tr, mn, desc in names]}

with open("app/src/main/assets/allah_names.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=1)
print("wrote", len(names), "names")
